version: '3'

services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - '5000:5000'
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
